apiVersion: apps/v1
kind: Deployment

metadata:
  name: employee-management

spec:
  replicas: 3

  selector:
    matchLabels:
      app: employee-management

  template:
    metadata:
      labels:
        app: employee-management

    spec:
      containers:
        - name: employee-management
          image: harshalmane19/employee-management:v1
          imagePullPolicy: Never

          ports:
            - containerPort: 8080
